
EXPORT TO q3a_result.csv OF DEL MODIFIED BY NOCHARDEL 
WITH MON AS(SELECT DOSAGE_UNIT,YEAR(TRANSACTION_DATE) ||
CASE 
    WHEN (  CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
         THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
    ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2))
END AS YEARDATE 
FROM cse532.dea_ny),
ABC AS (SELECT YEARDATE,SUM(DOSAGE_UNIT) AS MONTHLY_COUNT 
FROM MON
GROUP BY YEARDATE)


SELECT YEARDATE,MONTHLY_COUNT,AVG(MONTHLY_COUNT) OVER (ORDER BY YEARDATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTH
FROM ABC;


